apiVersion: v2
name: dnsweaver
description: Automatic DNS records for containers, VMs and clusters
type: application
version: 1.0.0
appVersion: "1.0.0"
home: https://github.com/maxfield-allison/dnsweaver
sources:
  - https://github.com/maxfield-allison/dnsweaver
maintainers:
  - name: maxfield-allison
    url: https://github.com/maxfield-allison
keywords:
  - dns
  - dns-automation
  - kubernetes
  - docker
  - proxmox
  - incus
  - external-dns
  - traefik
  - ingress
  - split-horizon
  - self-hosted
  - homelab
  - technitium
  - pihole
  - adguard
icon: https://raw.githubusercontent.com/maxfield-allison/dnsweaver/main/docs/assets/brand/icon-512.png
